### ISSUE TITLE
Добавить подсказку, что id уже используется

### ISSUE THREAD

**Issue by KIBORG04** [Ertanic/robust-lsp#2]
```yml
- type: entity
  id: aboba

- type: entity
  id: aboba <- !!!duplicated id definitive!!!
  ```
